### ISSUE TITLE
compBuildOrder depreciated > Cabal-1.16.0.3

### ISSUE THREAD

**Issue by m15k** [deech/fltkhs#1]
looks like `compBuildOrder :: [ComponentName]` has been depreciated in cabal-1.18+ in favor of `componentsConfigs :: [(ComponentName, ComponentLocalBuildInfo, [ComponentName])]`

**Comment by crockeea** [comment]
@deech Any progress on this? Your [CPlusPlusBindings](https://github.com/deech/CPlusPlusBindings) example won't compile due to missing `compBuildOrder`.

**Comment by deech** [comment]
Yes, `fltkhs` should just work with `stack install` now. Unfortunately the other repo you linked is unmaintained so no effort has been made to keep it updated with the latest version of Cabal. If you are using it for something please open an issue on that repo and I'll do my best to get it working again.

**Comment by deech** [comment]
Closing as this issue is now fixed by requiring Cabal >= 1.20.
