### ISSUE TITLE
FL_Tile not wrapped?

### ISSUE THREAD

**Issue by ocharles** [deech/fltkhs#10]
I might have missed something, as this is the first widget I looked for - but it doesn't seem like this library wraps http://www.fltk.org/doc-1.3/classFl__Tile.html

**Comment by deech** [comment]
No, it doesn't yet. Sorry. I don't have 100% coverage, more like 85% or so. It is covered on the C side so if this is a pressing need I can add it relatively quickly.

The list of currently wrapped widgets is listed here: http://hackage.haskell.org/package/fltkhs-0.1.0.2/docs/Graphics-UI-FLTK-LowLevel-FLTKHS.html#g:9

**Comment by ocharles** [comment]
No problem! I'll keep my eyes on this issue, so I know when I can start work on my 3D modelling software :)

**Comment by deech** [comment]
Will do! Thanks for the feedback. Also is there anything else you're seeing that you might need but isn't wrapped? If there's more I can maybe cut another release.

**Comment by ocharles** [comment]
Haven't got much further, was mostly just curious to see if FLTK had what I wanted. The core features I need are the ability to render a `diagrams` image to a widget (and receive mouse input) - I think I read that FLTK has Cairo support, is that exposed in this library? I also need a single tile in the tile editor to be rendered by GL - I know there is GLWindow but I'm not sure if that's what I want. Mostly daydreaming at the moment :)

**Comment by deech** [comment]
The `Cairo` functionality is currently not wrapped. Fl_Tile has been added. I think the Cairo wrappers belong in another package, maybe `fltkhs-cairo` or something, but it would incur a dependence on the Haskell `cairo` bindings. I'll work on that shortly.

**Comment by deech** [comment]
k
