### ISSUE TITLE
how to get a width of font / label?

### ISSUE THREAD

**Issue by dixie** [deech/fltkhs#100]
Hello,

I'm trying to set appropriate width of table columns but I'm not able to find function, which would provide dimensions of current font, especially width of font. 

In FLTK seems to be available this module: https://www.fltk.org/doc-1.4/group__fl__attributes.html

Are such a functions available in FLTKHS? How to measure size of font?

Thanks,
Radoslav Dorcik

**Comment by deech** [comment]
It's available `Draw.chs` so for `fl_width` you can use https://github.com/deech/fltkhs/blob/master/src/Graphics/UI/FLTK/LowLevel/Draw.chs#L485.

**Comment by dixie** [comment]
Thank you, it works, I overlooked Draw module.
