### ISSUE TITLE
TextDisplay seems to be missing xyToPosition

### ISSUE THREAD

**Issue by plredmond** [deech/fltkhs#101]
`TextDisplay` seems to be missing an `xyToPosition` ([`Fl_Text_Display::xy_to_position`](https://www.fltk.org/doc-1.4/classFl__Text__Display.html#a53327590afe31328051d4daa4cc5af75)) which would complement the extant `positionToXy`.

Here's an example app that uses `xy_to_position` to manipulate the character under the cursor: https://gist.github.com/plredmond/5e91aab1dff5f7140d71ea2dee63dbe4

Are there any plans to add this? I can try :)) but I'm new to chs so let's see..

**Comment by plredmond** [comment]
Well, I got part of the way through implementing an `xyToPosition` function in `TextDisplay.chs` and then the compiler pointed this out:
```
c2hs: Errors during expansion of binding hooks:

src/Graphics/UI/FLTK/LowLevel/TextDisplay.chs:136: (column 8) [ERROR]  >>> Unknown identifier!
  Cannot find a definition for `Fl_Text_Display_xy_to_position' in the header file.
```
I looked at `TextDisplay.chs.h` and then `Fl_Text_DisplayC.h` and indeed, there is no such exported function signature. I wonder if I can add it..

**Comment by plredmond** [comment]
Ah, finally, after looking under the `./c-src/` directory I can see that the bundled version of FLTK doesn't include `Fl_Text_Display::xy_to_position`! I'm not sure how to proceed short of updating the bundled version...

**Comment by deech** [comment]
If you can tack it onto the [end](https://github.com/deech/fltkhs/blob/master/c-src/Fl_Text_DisplayC.cpp#L77) of the existing `Fl_Text_Display` derived class, maybe something like:
```
int Fl_Derived_Text_Display::position_to_xy(int x, int y) {
  return Fl_Text_Display::position_to_xy(x,y);
```
and add something like the following to the [end](https://github.com/deech/fltkhs/blob/master/c-src/Fl_Text_DisplayC.cpp#L640) of the extern'ed list:
```
FL_EXPORT_C(int, Fl_Text_Display_position_to_xy)(fl_Text_Display o, int x, int y) {
    return (static_cast<Fl_DerivedText_Display*>(o))->position_to_xy(x,y);
}
```
and then add to the [end](https://github.com/deech/fltkhs/blob/master/c-src/Fl_Text_DisplayC.h#L226) of the list in the header file something like:
```
FL_EXPORT_C_HEADER(int,Fl_Text_Display_position_to_xy,(fl_Text_Display o, int x, int y));
```

It's now available to C2HS on the Haskell side.

**Comment by deech** [comment]
You also probably want to add to [derived class](https://github.com/deech/fltkhs/blob/master/c-src/Fl_Text_DisplayC.h#L25):
```
int position_to_xy(int x, int y);
```
If you want to expose the `posType` argument you'll have to add it that to the end of the argument list as well and use a `Maybe PositionType` for the [Haskell](https://github.com/deech/fltkhs/blob/master/src/Graphics/UI/FLTK/LowLevel/Fl_Types.chs#L117) side.

**Comment by deech** [comment]
Also `stack` doesn't always pick up changes to the `C` side of things so you'll probably have to blow away your `stack` files and start over:
```
make clean
stack clean
rm -rf .stack-work
stack build --flag fltkhs:bundled
```
