### ISSUE TITLE
Docs missing for FL.scrollbarSize

### ISSUE THREAD

**Issue by ericu** [deech/fltkhs#107]
I couldn't find documentation for scrollbarSize; I expect it should be in http://hackage.haskell.org/package/fltkhs-0.1.0.1/docs/Graphics-UI-FLTK-LowLevel-FL.html.  I knew it existed from the fltk docs, but I had to dig through your source to find out where it was and what it was called in fltkhs.  I didn't check what other functions might be missing.

**Comment by deech** [comment]
I see [it](http://hackage.haskell.org/package/fltkhs-0.7.0.4/docs/Graphics-UI-FLTK-LowLevel-FL.html#v:scrollbarSize). You seem to be looking a super old version.

**Comment by ericu** [comment]
Right you are!  Sorry about that--I blindly followed what turned up in Google's results.  Sorry about the noise.

**Comment by ericu** [comment]
Huh.  Oddly, every other page of docs I have open is in 0.7.0.4; just that one was the old one.
