### ISSUE TITLE
What is the purpose of Graphics.UI.FLTK.LowLevel.Base.Button?

### ISSUE THREAD

**Issue by mitchellwrosen** [deech/fltkhs#112]
I see that `Button` extends `Base.Button`, but the four functions mentioned in its docs (`handle`, `hide`, `resize`, and `showWidget`) all exist at the `Widget` level.

**Comment by deech** [comment]
These are functions that can be overridden on the Haskell side and are typically the bits of the application that need the most debugging. Having them "pinned" to `Button` makes for much nicer error messages on the Haskell side, makes it easier to work with gdb when needed and, maybe this is fixed now, but I found it throws off profiling as well.

**Comment by mitchellwrosen** [comment]
Gotcha, thanks!
