### ISSUE TITLE
Clarify how/when to call `destroy`

### ISSUE THREAD

**Issue by mitchellwrosen** [deech/fltkhs#120]
I believe the `destroy` function calls the C++ destructorsince I couldn't find a function called `destroy` in any of the FLTK widgets' APIs. If so, it would be helpful to document somewhere when you should explicitly call `destroy`, if you need to at all. Thanks!

**Comment by deech** [comment]
Great idea! If I could do it over I would have gone with `delete` to match C++ destructor calls.
