### ISSUE TITLE
Can't resizeScrolledBase in 0.8.0.0

### ISSUE THREAD

**Issue by ericu** [deech/fltkhs#123]
I'm upgrading from 0.7.0.4 to 0.8.0.0 and having a couple of issues.  Here's the first:

I have a Scrolled created using scrolledCustom, in which I override resizeCustom.
I still want to call the parent class's resizing code, so previously I was using resizeSuper.  If I'm reading things right, the new way to do that is to call resizeScrolledBase, but I can't get that to compile.

"scrolled" is a Ref Scrolled; "newRect" is a Rectangle.

Old code:
`    resizeSuper scrolled newRect`

New compiler error:
>    Graphics.UI.FLTK.LowLevel.Hierarchy.ResizeSuper is not supported by  Graphics.UI.FLTK.LowLevel.Hierarchy.CScrolledGraphics.UI.FLTK.LowLevel.Hierarchy.GroupFuncs

First try at the new way:
`    resizeScrolledBase scrolled newRect`

Compiler error:
>   Couldn't match type ‘Graphics.UI.FLTK.LowLevel.Hierarchy.CScrolled Group’
                     with ‘Graphics.UI.FLTK.LowLevel.Hierarchy.CScrolledBase
                             Graphics.UI.FLTK.LowLevel.Hierarchy.GroupBase’
      Expected type: Ref Graphics.UI.FLTK.LowLevel.Hierarchy.ScrolledBase
        Actual type: Ref Scrolled

Second try:
`   resizeScrolledBase (safeCast scrolled) newRect`

Compiler error:
>   Graphics.UI.FLTK.LowLevel.Hierarchy.CScrolled is not a kind of Graphics.UI.FLTK.LowLevel.Hierarchy.CScrolledBase

I see that Widget and WidgetBase appear to have a different relationship than Scrolled and ScrolledBase:

`type WidgetBase = CWidgetBase Base
type Widget = CWidget WidgetBase`

`type ScrolledBase = CScrolledBase GroupBase
type Scrolled = CScrolled Group`

Is that the problem?

Thanks!  Apart from these issues [which aren't killing me, since I can always run the older version], things are going great.  I'm porting an old fltk C++ app I wrote a couple of decades ago into Haskell to expand it further, and it's been surprisingly easy.

**Comment by ericu** [comment]
I just noticed I had the same problem with hideDoubleWindowBase; I couldn't call it with a safeCast of a Ref DoubleWindow.  But I saw these definitions:

`type DoubleWindowBase = CDoubleWindowBase WindowBase Source#
type DoubleWindow = CDoubleWindow WindowBase`

...so I tried hideWindowBase instead, and that compiled.  I don't know if it's correct, but it looks like it's probably working.

**Comment by deech** [comment]
You're absolutely right,  I messed up the hierarchies when I refactored. I'll audit the rest, fix what I find and re-release. For overrideable widgets the pattern should always be:
```
type Foo = CFoo FooBase
```

 Thanks for the report!
