### ISSUE TITLE
0.8.0.0: Couldn't match type ‘ScrollbarMode’ with ‘GHC.Word.Word8’

### ISSUE THREAD

**Issue by ericu** [deech/fltkhs#124]
I'm upgrading from 0.7.0.4 to 0.8.0.0 and hitting this compile issue.

This code, which worked fine previously:

`  setType scrolled BothScrollBar`

Now yields this compile error:

>Couldn't match type ‘ScrollbarMode’ with ‘GHC.Word.Word8’
        arising from a use of ‘setType’

In case it's relevant, here are my includes from that file [yes, they're messy--it's a work in progress =*)].

`import qualified Graphics.UI.FLTK.LowLevel.FL as FL
import Graphics.UI.FLTK.LowLevel.Fl_Types
import qualified Graphics.UI.FLTK.LowLevel.Fl_Enumerations as FL
import Graphics.UI.FLTK.LowLevel.FLTKHS (Widget, Window, Group, DoubleWindow,
                                         Scrolled, Box, boxNew, Tree, treeNew,
                                         MenuBar, menuBarNew, MenuItem,
                                         MenuItemLocator(..), findIndex,
                                         MenuItemName(..),
                                         clearSubmenu, nativeFileChooserNew,
                                         NativeFileChooser,
                                         NativeFileChooserType(..),
                                         NativeFileChooserUserAction(..), clear,
                                         setTitle, getFilename,
                                         setShowroot, setSelectbox, begin, end,
                                         showWidget, setCallback, hide,
                                         defaultCustomWidgetFuncs,
                                         CustomWidgetFuncs(..),
                                         defaultCustomWindowFuncs, getRectangle,
                                         toRectangle, scrolledCustom, setType,
                                         widgetCustom, windowNew, windowCustom,
                                         doubleWindowCustom, sizeRangeWithArgs,
                                         OptionalSizeRangeArgs(..), add,
                                         addResizable, resizeScrolledBase,
                                         resizeSuper,
                                         resize, safeCast,
                                         redraw, Height(..))`

**Comment by deech** [comment]
I bet this is related to the previous issue where the `Scrolled` hierarchy isn't right so it's falling through to the `setType` of `Widget`. 

Also as an aside, is there any reason for the individual imports? I re-export everything in `import Graphics.UI.FLTK.LowLevel.FLTKHS` to save you from that bother.

**Comment by ericu** [comment]
I don't usually like to import huge numbers of symbols without qualification.  It sometimes causes conflicts with other imported or local symbols, and sometimes I come back to the file months later and can't figure out which library fromThing came from or what it does.  However, in this case it's gotten ridiculous, and I should either switch to a qualified import or just give up and import the whole thing and keep the file as small as possible.  It started quite small, but I've been adding to it rapidly as the UI starts to take shape.
