### ISSUE TITLE
`replMain` takes up 100% of one CPU

### ISSUE THREAD

**Issue by deech** [deech/fltkhs#127]
@ericu I think this is fixed in the latest release. I wait a 1/10th of a second before each iteration in `replMain` which takes the load off the CPU and seems responsive enough. If you have a chance to test let me know how it works.

**Comment by ericu** [comment]
Yup, that's nailed it.  Thanks!

I tested in 0.8.0.2 with my app, and the CPU usage is negligible unless I'm actually doing something heavy in my own code.
