### ISSUE TITLE
`flChoice` and `flInput` may crash with a format string

### ISSUE THREAD

**Issue by deech** [deech/fltkhs#140]
Currently if the first argument to `flChoice` and `flInput` a format string it might lead to a segfault because no format arguments are allowed. Not sure of the easiest way around that, is there a reliable format string parser that can test it and reject the call with a suitable error message?
@ericu, any thoughts?

**Comment by ericu** [comment]
Ah, that's a good point.  As a simple stopgap, we could just escape all '%' with a second '%' to prevent their being interpreted.

**Comment by deech** [comment]
I'm less of a C expert, are there any edge cases there? Stop gaps like that tend to become permanent. :)

**Comment by ericu** [comment]
It seems safe to me; it's how I'd print a literal format string if you didn't want it interpreted.
It's also harmless if nobody sends us a format string.

It also applies to flPassword and flMessage.

https://github.com/deech/fltkhs/pull/141

**Comment by deech** [comment]
Thanks!
