### ISSUE TITLE
Return function pointer from `openCallback` so it can be freed.

### ISSUE THREAD

**Issue by deech** [deech/fltkhs#147]
@mtolly I've modified [`openCallback`](https://github.com/deech/fltkhs/commit/c55aa9198088198e83060276114fcb8087872734) so `freeHaskellFunPtr` can be called on it when appropriate. Please close this issue when you see this. Thanks!

**Comment by mtolly** [comment]
Looks good, thank you!
This isn't an issue I can close, since you opened it?
