### ISSUE TITLE
after using setIcon on window it doesn't display application 

### ISSUE THREAD

**Issue by dixie** [deech/fltkhs#152]
Hello!

my application worked perfectly, but after using setIcon (to have nice icon in taskbak) my application is not displayed anymore (or is it frozen?):

 mimg <- pnmImageNew "dataviewer.pnm"
 case mimg of
    Left msg  -> flAlert $ T.pack $ show msg
    Right img -> do
      setIconlabel window "dataviewer.pnm"
      setIcon window (Just img)

When I comment out that "setIcon" part, it works again perfectly.

What could be a problem? 

Environment:
- MS/Windows 10 
- fltkhs 0.8.0.2
- stack (x86_64-windows-ghc-8.4.3)

Remark: I used also png. my png icon is in attachment. the same effect.

Icon:
![dataviewer](https://user-images.githubusercontent.com/44675/67018177-22094080-f0fb-11e9-9ba5-a0427412326e.png)

**Comment by deech** [comment]
I _think_ I may have [fixed your issue](https://github.com/deech/fltkhs/commit/b26db95b2f1058af373d81938ac89bbfff17563c) . Would you mind pulling and trying again?

**Comment by dixie** [comment]
thank you! I will try to test it, but it will take little time, because I'm using stack and I'm not familiar how I can use fltkhs version from git in stack build.

**Comment by deech** [comment]
Ah yes, here's how to do that:
1. Create a directory like `icon-test` or something.
2. Clone your project into that directory
3. Clone `fltkhs` into that directory
4. Add this minimal `stack.yaml` to the root of that directory ( you might have to add your own customizations ) :
```
resolver: lts-13.28
allow-newer: true
packages:
- 'fltkhs'
- 'your-project'
```
5. Do `stack build --flag fltkhs:bundled` + whatever other flags are needed for your project.
6. Wait ... :)
7. `stack exec your-project-executable`.

**Comment by dixie** [comment]
thank you very much! It works now :)

![image](https://user-images.githubusercontent.com/44675/68843186-f95b7300-06c7-11ea-8ec3-4cf1fb6c5f9e.png)
