### ISSUE TITLE
Adding a Scrolled via FLUID generates wrong "scrollNew" call instead of "scrolledNew"

### ISSUE THREAD

**Issue by oswald2** [deech/fltkhs#156]
Adding a Scrolled in a FLUID file issues a call to "scrollNew" which is not known and should be "scrolledNew"

Issued message: 

> aurisi>     • Variable not in scope:
> aurisi>         scrollNew :: Rectangle -> Maybe a0 -> IO (Ref a3)
> aurisi>     • Perhaps you meant ‘scrolledNew’ (imported from Graphics.UI.FLTK.LowLevel.FLTKHS)
> aurisi>    |
> aurisi> 25 |     mainScrolled <- scrollNew  (toRectangle (25,25,1730,1000)) Nothing;
> aurisi>    |                     ^^^^^^^^^

Version: fltkhs-0.8.0.2

**Comment by deech** [comment]
Fixed. https://github.com/deech/fltkhs/commit/0dc7dd47528c6851a540a3b227bbe063586c0b6c
