### ISSUE TITLE
cabal-install 3.4.0.0 breaks installation

### ISSUE THREAD

**Issue by vmchale** [deech/fltkhs#173]
Building works fine, but when I try to use it in a project:

```
cabal: The following package dependencies were requested
--dependency='fltkhs=fltkhs-0.8.0.3-accf656aa1084c833eb911f7cdc905304bc7349170386eed04847ea1e85f67ca'
however the given installed package instance does not exist.
```

```
vanessa@vanessa-dell:~/dev/haskell/dickinson/dickinson-fltk$ cabal --version
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library
```

Thanks!

**Comment by deech** [comment]
Which branch did you try? Ongoing dev is happening in [TheGreatConsolidation](https://github.com/deech/fltkhs/tree/TheGreatConsolidation).

**Comment by vmchale** [comment]
Oh, nvm! Seems to work with `source-repository-package` at least. Thank you for the continued work! :pray:

**Comment by vmchale** [comment]
Hmm, this might be related to `source-repository-package` vs. installations from Hackage, I'll have to see what happens with the next release!
