### ISSUE TITLE
Segfault when recreating FLTK Example 1

### ISSUE THREAD

**Issue by jdreaver** [deech/fltkhs#18]
Hello! I was trying to recreate [Example 1](http://www.fltk.org/doc-2.0/html/example1.html) from the fltk docs and I got a segfault. Here is the example program:

```haskell
module Main where

import qualified Graphics.UI.FLTK.LowLevel.FL as FL
import Graphics.UI.FLTK.LowLevel.Fl_Enumerations
import Graphics.UI.FLTK.LowLevel.FLTKHS

main :: IO ()
main = do
  w1 <- windowNew (Size (Width 300) (Height 180)) Nothing (Just "Hello!")
  begin w1
  let labelRect = Rectangle (Position (X 20) (Y 40)) (Size (Width 260) (Height 100))
  label <- widgetCustom labelRect (Just "Bob") defaultCustomWidgetFuncs
  setBox label UpBox
  setLabelfont label helveticaBoldItalic
  setLabelsize label (FontSize 36)
  setLabeltype label ShadowLabel
  end w1
  showWidget w1
  _ <- FL.run
  return ()

```

Am I doing something wrong? I installed FLTK like is shown in the README. I am running in a cabal sandbox, and the examples work. If I use an Output with `outputNew` instead of `widgetCustom`, I don't get a segfault, but I see no text (this is an issue for later I think, I thought the segfault was more pertinent, and I am just mentioning it because I think it indicates the problem is with `widgetCustom`).

FYI: I am trying to learn FLTK as I use this library (I have a ton of experience with PyQt, but not FLTK). As I go, I want to make a pull request with some heavily commented examples, just like FLTK has. 

Thanks for your work on this library!

**Comment by deech** [comment]
Ah, this is my mistake not yours.

The reason you are getting the segfault is that `Widget` has no default `draw` function. `defaultCustomWidgetFuncs` just creates a null pointer because there is nothing else it can do. When the `Window` tries to `draw` the widget it hits the null pointer and segfaults.

When you use `Output`, a widget with a default drawing routine you don't see this.

I think I'm going to change the widget constructor to take a drawing function so the user has to provide one.

What do you think?

**Comment by jdreaver** [comment]
Ah, I understand now.

> I think I'm going to change the widget constructor to take a drawing function so the user has to provide one.

That sounds like a great solution. IMO, if a drawing function is required, the types should reflect that. No null pointers in Haskell! :smile: 

What drawing function is the FLTK example program using? Does a "default drawing function" exist for widgets? It looks like the default `Widget` in FLTK is like a label. That seems kind of weird to me. (Sorry if my terminology is a little off, I'm still learning.)

**Comment by deech** [comment]
No prob.

The supported example program I linked uses the `Fl_Box` widget which has it's own drawing routine.

I've recreated the example from the supported version and I can confirm it works:

```
module Main where

import qualified Graphics.UI.FLTK.LowLevel.FL as FL
import Graphics.UI.FLTK.LowLevel.Fl_Enumerations
import Graphics.UI.FLTK.LowLevel.FLTKHS

main :: IO ()
main = do
  w1 <- windowNew (Size (Width 300) (Height 180)) Nothing (Just "Hello!")
  begin w1
  let labelRect = Rectangle (Position (X 20) (Y 40)) (Size (Width 260) (Height 100))
  label <- boxNew labelRect (Just "Bob") Nothing
  setBox label UpBox
  setLabelfont label helveticaBoldItalic
  setLabelsize label (FontSize 36)
  setLabeltype label ShadowLabel
  end w1
  showWidget w1
  _ <- FL.run
  return ()
```

**Comment by jdreaver** [comment]
For some reason I didn't see your last part about me using the docs from and unsupported version of FLTK. I understand perfectly why my program doesn't work now. I can confirm that your example works. Thanks for your help!

**Comment by deech** [comment]
Uploaded a fixed version to Hackage http://hackage.haskell.org/package/fltkhs.

**Comment by deech** [comment]
I have made some changes that make working with custom widgets a little easier. This includes some breaking API changes. In your example:

```
label <- boxNew labelRect (Just "Bob") Nothing
```

is now:

```
label <- boxNew labelRect (Just "Bob")
```

The new version (0.3.0.0) is now up on Hackage. Thanks for bringing this issue to light. It's good to make these changes while the library is still young. :)

**Comment by jdreaver** [comment]
Yeah, that is a lot cleaner for the probably most common case of non-custom widgets. Thanks!
