### ISSUE TITLE
Use with cabal repl

### ISSUE THREAD

**Issue by jdreaver** [deech/fltkhs#21]
Hello! I am 90% sure this is user error on my part, but I am posting here for help. I have a project that uses `fltkhs` (just a number of simple executable files that I am making small testing programs with). All of the programs work great and can find the compiled fltk modules, thanks to, I'm assuming, the following line in the `.cabal` files:

```
ghc-Options: -pgml g++ "-optl-Wl,--whole-archive" "-optl-Wl,-Bstatic" "-optl-Wl,-lfltkc" "-optl-Wl,-Bdynamic" "-optl-Wl,--no-whole-archive"
```

However, when I run `cabal repl`, I think the fltk files are not found. I get the following error:

```
 $ cabal repl
Preprocessing executable 'basic' for testing-fltkhs-0.1.0.0...
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
<command line>: can't load .so/.DLL for: /home/david/scratch/fltkhs/.cabal-sandbox/lib/x86_64-l
inux-ghc-7.10.2/fltkh_6U9r2TsApb78yY6ZxCRDjK/libHSfltkhs-0.3.0.0-6U9r2TsApb78yY6ZxCRDjK-ghc7.10
.2.so (/home/david/scratch/fltkhs/.cabal-sandbox/lib/x86_64-linux-ghc-7.10.2/fltkh_6U9r2TsApb78
yY6ZxCRDjK/libHSfltkhs-0.3.0.0-6U9r2TsApb78yY6ZxCRDjK-ghc7.10.2.so: undefined symbol: _ZTVN10__
cxxabiv120__si_class_type_infoE)                                                              
```

I am on Arch Linux, which comes with another `fltk` package. That package doesn't work with `fltkhs`, so I downloaded and manually compiled `fltk` version 1.3.3 like you said in the README. Again, the example work fun when executed with `cabal run`. I think the error here is because `cabal repl` is using the Arch Linux version of `fltk`, and not the version I manually compiled.

My question is, does anyone use `cabal repl` when working on `fltkhs` projects? Is there anything special you have to do to get it to work? Thanks in advance!

**Comment by deech** [comment]
Unfortunately loading FLTKHS programs into GHCI is not supported right now because of the error you're running into.

I ran into the same issues and was unable to work it out for the release. I should have added a section to the README but I plain forgot. I'll do that.

REPL support is certainly on the roadmap, but it looks like I'm going to need some help with that.

Sorry.

**Comment by jdreaver** [comment]
No need to apologize! 

Do you know why it's happening at all? I can take a look.

**Comment by jdreaver** [comment]
I've determined that the symbol `_ZTVN10__cxxabiv120__si_class_type_infoE` is from `libstdc++`. No idea how that trips up cabal repl though.

**Comment by deech** [comment]
Me neither. I know that libstdc++ is linked against fltkhs when making the statically linked version of the library. It would be ideal if it was possible to load statically linked libs into GHCi but that doesn't appear to be the case.

**Comment by jdreaver** [comment]
I fixed the libstdc++ error by adding `extra-libraries: stdc++` to the library section of the cabal file. Now I am getting another error when running cabal repl:

```
ByteCodeLink: can't find label
During interactive linking, GHCi couldn't find the following symbol:
  fl_define_FL_ROUND_UP_BOXC
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org
```

This is weird because running `nm` on the libHSfltkhs so file and grepping for that missing symbol works:

```
 $ nm -D dist/build/libHSfltkhs-0.3.0.1-3YgBiCkkmtH5Xk75knJmQq-ghc7.10.2.so | grep fl_define_FL_ROUND_UP_BOXC                                                                                                         
0000000000833560 T fl_define_FL_ROUND_UP_BOXC
```

Of course, I checked that the examples still work. At least I made progress!

**Comment by jdreaver** [comment]
Hey @deech, I've seen all of the commits you made recently; very cool! Also, good luck with your presentation at the Compose conference coming up!

I noticed you said that `cabal repl` won't work in GHC 7.10 due to a regression ([link here](https://ghc.haskell.org/trac/ghc/ticket/10568) to GHC bug report). I think that bug is fixed in GHC 7.10.3 though, as it says at the bottom of the bug report. Have you tried it on GHC 7.10.3? If not, I might find some time to test it this week.

**Comment by deech** [comment]
Thanks for the encouragement! I tried it with 7.10.3 and the latest Cabal. No dice. :(

**Comment by deech** [comment]
BTW, if you're in the audience, do say hello.

**Comment by jdreaver** [comment]
Ah, I'll try to debug the REPL stuff soon. I'm pretty busy though at the moment haha.

I won't be able to attend the conference :/ I'll be sure to watch the videos when they are uploaded though!

**Comment by deech** [comment]
I can confirm that it works with 7.8.x.

**Comment by bmmoore** [comment]
In your fltkhs-hello-world example, I get this error from `stack repl` or `cabal new-repl`:

    user specified .o/.so/.DLL could not be loaded (libfltkc-dyn.so: cannot open shared object file: No such file or directory)
    Whilst trying to load:  (dynamic) fltkc-dyn
    Additional directories searched: (none)

After that, `stack repl` quits but `cabal new-repl` goes on to give a prompt `Prelude Main>`, from which I can import FLTK modules, but get an error when trying to call anything:

    Prelude Main> import Graphics.UI.FLTK.LowLevel.FL
    Prelude Graphics.UI.FLTK.LowLevel.FL Main> :t run
    run :: IO Int
    Prelude Graphics.UI.FLTK.LowLevel.FL Main> run
    /usr/local/lib/ghc-8.0.1/bin/ghc: symbol lookup error: /home/brandon/.cabal/store/ghc-8.0.1/fltkhs-0.5.1.4-605f1ef002b67a1aac04c291f4e3b03a3e2d76ea2a60e540481e0357b36ed5b6/lib/libHSfltkhs-0.5.1.4-605f1ef002b67a1aac04c291f4e3b03a3e2d76ea2a60e540481e0357b36ed5b6-ghc8.0.1.so: undefined symbol: Fl_run

**Comment by deech** [comment]
Hi,
I just fixed your issue but unfortunately working with the REPL isn't as smooth as it could be. Can you re-clone the `fltkhs-hello-world` repo and as before do `stack repl`? But instead of just `:main` do `forkIO main`. The GUI should now pop up. However the REPL has an issue where the GUI remains visible even after hitting the `X` to close the window. If you do `forkIO main` again it will disappear and you should now see the new instance. REPL usage is undocumented because of this usability issue.

**Comment by bmmoore** [comment]
Thanks! I mostly care about it loading cleanly so intero/ghc-mod work. Actually running a GUI from the REPL is nice, but less important.

**Comment by deech** [comment]
Great. If this does what you want do you mind closing?

**Comment by jdreaver** [comment]
I made this issue originally, I'll go ahead and close. Thanks!
