### ISSUE TITLE
c2hs version constraints

### ISSUE THREAD

**Issue by sdx23** [deech/fltkhs#22]
Building with c2hs 0.17.2 (debian jessie default) fails:

    src/Graphics/UI/FLTK/LowLevel/Button.chs:116: (column 66) [ERROR]  >>> Missing "out" marshaller!
    There is no default marshaller for this combination of Haskell and C type:
    Haskell type: CInt
    C type      : CInt

0.26.2 is fine. Not sure, however, how to include such a constraint in the cabal file, so this is just an issue report instead of a PR.

**Comment by deech** [comment]
The new version does have those constraints. Thanks for the report!
