### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by jaramago** [deech/fltkhs#3]
I got this error after cabal build

```
*** Compiling DerivedText_Editor.cpp...
DerivedText_Editor.cpp: In member function ‘void DerivedText_Editor::remove_key_binding(int, int, DerivedText_Editor::Key_Binding_With_Callback**)’:
DerivedText_Editor.cpp:91:36: error: ‘last’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   if (last) last->next = curr->next;
                                    ^
cc1plus: all warnings being treated as errors
```

This is on gcc 4.9.2, ghc 7.8.4 and on a Archlinux 64bits system.

If I disable -Werror on c-src/Makefile.in (or initialize the "last" pointer in the cpp code) then the compilation continue , but fails later on linking fase. Lot of line similar to:
```
undefined reference to `Fl_Menu_Button::Fl_Menu_Button(int, int, int, int, char const*)' 
```
I try to resolve it later, and post any further ideas.

**Comment by deech** [comment]
Thanks for the report.

Unfortunately my version of g++:

```
g++ (Ubuntu/Linaro 4.8.1-10ubuntu9) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

did not catch that warning at all.

The error you're getting happens if the FLTK libs are not found in the library path. Did you compile by hand or use a package manager?

**Comment by jaramago** [comment]
Ok, I've used the package manager from my distro to get the fltk version1.3.3-4, and the library path is /usr/include/FL. I have remove it and installed from sources following your README instrucctions AND COMPILATION IS OK, like a charm :-)
Maybe my distro package lacks some libraty headers code or something like that , Idon't know.
