### ISSUE TITLE
fltk_images lib missing on OSX El Capitan

### ISSUE THREAD

**Issue by simonmichael** [deech/fltkhs#31]
After `brew install fltk --devel` and doing `stack build` in the fltkhs-hello-world project, I get
```
    *** Linking libfltkc.a...
    /Library/Developer/CommandLineTools/usr/bin/ranlib: file: ../c-lib/libfltkc.a(fl_utf8C.o) has no symbols
    *** Linking libfltkc-dyn.dylib...
    ld: library not found for -lfltk_images
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

http://hackage.haskell.org/package/fltkhs-0.4.0.5/docs/Graphics-UI-FLTK-LowLevel-FLTKHS.html#g:4 mentions "fltk_images" very briefly, but I don't see it in homebrew.

**Comment by deech** [comment]
I ran into this problem last night and updated the `fltkhs-hello-world` repo yesterday. Can you confirm that the latest commit is `Up FLTKHS Dependency`. If not, could you `git pull` and try again?

The issue is that on El Capitan for some reason the linker does not look in `/usr/local/lib` which is where brew sticks `libfltk_images`. I'm not sure why this is the case but adding `-L/usr/local/lib` to the Makefile made the problem go away.

**Comment by simonmichael** [comment]
> Can you confirm that the latest commit is Up FLTKHS Dependency.
> 
Yes, it is.

**Comment by deech** [comment]
Hmm ... I have brand new El Capitan machine and removed and installed `fltk` using `brew install --devel fltk` and successfully installed the example. 

Shot in the dark, in your `stack.yaml` file under `extra-deps`, it does list `fltkhs-0.4.0.5` and not `fltkhs-0.4.0.4` or some other version right?

**Comment by deech** [comment]
I have also updated the Github README with better instructions. Thanks for that feedback!

**Comment by simonmichael** [comment]
The README seems much clearer. Unlike those instructions, here `fltk-config --version` reports 1.3.3. I have fltk-1.3.3-r10866.tar.gz. I ran `brew update` to be sure I had the latest from homebrew.

**Comment by simonmichael** [comment]
Oh, and thank you, for the valuable and not-so-fun work on making GUIs practical in Haskell. I'm glad these quick reports are helpful.

**Comment by deech** [comment]
Here's a shell session where I uninstall FLTK and re-install. I can only imagine that somehow your `fltk-config` is a hold-over from the time you tried to install from source. Can't imagine why that would be ...

```
$ brew --version
Homebrew 0.9.5 (git revision 01ef; last commit 2016-02-25)
$ brew update
Already up-to-date.

$ brew uninstall fltk
Uninstalling /usr/local/Cellar/fltk/1.3.3-r10866... (322 files, 5M)
$ fltk-config --version
-bash: /usr/local/bin/fltk-config: No such file or directory

$ brew install --devel fltk
==> Downloading http://fltk.org/pub/fltk/snapshots/fltk-1.3.x-r10866.tar.gz
Already downloaded: /Library/Caches/Homebrew/fltk-1.3.3-r10866.tar.gz
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/fltk/1.3.3-r10866 --enable-threads --enable-shared
==> make install
/usr/local/Cellar/fltk/1.3.3-r10866: 322 files, 5M, built in 48 seconds
$ ls -alh /usr/local/lib/libfltk_images.
libfltk_images.1.3.dylib  libfltk_images.a          libfltk_images.dylib      
$ ls -alh /usr/local/lib/libfltk_images.*
lrwxr-xr-x  1 deech  admin    56B Feb 25 15:16 /usr/local/lib/libfltk_images.1.3.dylib -> ../Cellar/fltk/1.3.3-r10866/lib/libfltk_images.1.3.dylib
lrwxr-xr-x  1 deech  admin    48B Feb 25 15:16 /usr/local/lib/libfltk_images.a -> ../Cellar/fltk/1.3.3-r10866/lib/libfltk_images.a
lrwxr-xr-x  1 deech  admin    52B Feb 25 15:16 /usr/local/lib/libfltk_images.dylib -> ../Cellar/fltk/1.3.3-r10866/lib/libfltk_images.dylib

$ fltk-config --version
1.3.4
$ which fltk-config
/usr/local/bin/fltk-config
```

**Comment by simonmichael** [comment]
Aha! I didn't notice that brew install was reporting failure to link a bunch of files (the list was so long). After `brew link --overwrite fltk`, all is well! stack build succeeds.

**Comment by deech** [comment]
Yay! I'll close your other issues as well. Thanks again for bearing with me.
