### ISSUE TITLE
brew install fltk ==> error

### ISSUE THREAD

**Issue by babusri** [deech/fltkhs#34]
brew install fltk

fltk: This formula either does not compile or function as expected on OS X
versions newer than Yosemite due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.

**Comment by deech** [comment]
This is a known issue with fltk and OSX > Yosemite. Please do:
```
brew install --devel fltk
```

Also see the Quick Install instruction for "El Capitan" on the main page for further instructions.

**Comment by babusri** [comment]
Thanks. 
In the instructions, you can add 'stack setup' before 'stack install'

You can close the issue.
