### ISSUE TITLE
TableRowSelectFlag type constructors not exposed.

### ISSUE THREAD

**Issue by deech** [deech/fltkhs#35]

**Comment by sboosali** [comment]
If this issue is still open, I can take a look at it. But I've never used c2hs before, so any context you have about fltkhs would help. (like whether this just slipped through, oe had a particular problem).

**Comment by deech** [comment]
This has been [fixed](https://github.com/deech/fltkhs/blob/master/src/Graphics/UI/FLTK/LowLevel/TableRow.chs#L6) but I forgot to close it. Thanks for offering to help!
