### ISSUE TITLE
add_fd?

### ISSUE THREAD

**Issue by mrak** [deech/fltkhs#37]
I wanted to add a callback for when a file descriptor has data to read.

I see equivalents for `add_check` and `add_idle`, but don't see one for `add_fd` unless I'm missing it.

**Comment by mrak** [comment]
Thank you so much!

**Comment by deech** [comment]
It has now been added to `master`. Additionally I've added a demo to `fltkhs-demos` (https://github.com/deech/fltkhs-demos/blob/master/src/Examples/fd-example.hs). Could you verify and close the issue if it works? Thanks!

**Comment by deech** [comment]
FYI this demo is the equivalent of `howto-add_fd-and-popen.cxx` in the `Examples` directory of `FLTK 1.3.3` source distribution.

**Comment by mrak** [comment]
I'll take a look when I have the chance this week. Thanks again!

**Comment by deech** [comment]
If this is fixed would you mind closing?

**Comment by mrak** [comment]
Sure thing -- thanks again
