### ISSUE TITLE
Too many library dependencies on Windows

### ISSUE THREAD

**Issue by jputcu** [deech/fltkhs#49]
Successful installed fltkhs-0.5.0.9 but linking my own app to the library fails:
~~~~
Linking dist\build\App\App.exe ...
g++: error: /mingw32/lib/libfltk_images.a: No such file or directory
g++: error: /mingw32/lib/libfltk_png.a: No such file or directory
g++: error: /mingw32/lib/libfltk_z.a: No such file or directory
g++: error: /mingw32/lib/libfltk_jpeg.a: No such file or directory
g++: error: /mingw32/lib/libfltk_gl.a: No such file or directory
g++: error: /mingw32/lib/libfltk_forms.a: No such file or directory
g++: error: /mingw32/lib/libfltk.a: No such file or directory
`g++' failed in phase `Linker'. (Exit code: 1)
~~~~

In `%APPDATA%\ghc\i386-mingw32-8.0.2\package.conf.d\fltkhs-0.5.0.9-KXyRP22dXDGGi8E4BCALOM.conf`
I notice the following linker flags:

~~~~
ld-options: -mwindows "-Wl,--enable-auto-import"
            "-Wl,--enable-runtime-pseudo-reloc" /mingw32/lib/libfltk_images.a
            /mingw32/lib/libfltk_png.a /mingw32/lib/libfltk_z.a
            /mingw32/lib/libfltk_jpeg.a /mingw32/lib/libfltk_gl.a -lglu32
            -lopengl32 /mingw32/lib/libfltk_forms.a /mingw32/lib/libfltk.a
            -lole32 -luuid -lcomctl32 -lstdc++
~~~~~

Wasn't expecting the dependency on the static libraries which I suspect are already in the `fltkhs` library.

**Comment by deech** [comment]
I'm trying it now on `fltkhs-hello-world`. My Windows machine is pretty slow so it's taking a while. In the meantime can you check that your app matches the skeleton's (cabal settings)[https://github.com/deech/fltkhs-hello-world/blob/master/fltkhs-hello-world.cabal#L37]?

**Comment by deech** [comment]
I reproduced it. Working on a fix.

**Comment by deech** [comment]
I just pushed a fix. Would you mind trying? If it works I'll upload to Hackage.

**Comment by deech** [comment]
I pushed up a new version to Hackage. `fltkhs-hello-world` etc. have also been updated to the `0.5.1.0`.

**Comment by jputcu** [comment]
App compiles and works, thanks.
