### ISSUE TITLE
Allow installation with fltk-1.3.3

### ISSUE THREAD

**Issue by jputcu** [deech/fltkhs#50]
Many linux distros still have the older `fltk-1.3.3`. Because `fltk-1.3.4` is backwards compatible we could make the build smarter to allow both.
This would make installing fltkhs very easy, just install the `fltk-dev` package and `cabal install fltkhs`.

**Comment by deech** [comment]
When I was coming up with install guides I was pretty torn on whether to tell people to install from the package manager or compile from scratch. At least on Arch and Debian I found that the packages led to runtime dependencies that didn't happen when compiling from scratch (eg. libjpeg, libpng).

Also while `1.3.4` is backwards compatible it does [add to the API](https://abi-laboratory.pro/tracker/timeline/fltk/) symbols to the API. I have in turn added bindings for them. I could go with `ifdef`'s and flags but I made the decision that for my own maintenance sanity I would track the latest stable version.

These are great thoughts, though and I like how you're thinking of making the install process easier. It was also primary on my mind when I was writing the package.

**Comment by deech** [comment]
Since I am tracking the stable version maybe it makes sense to bundle FLTK source, have Cabal build it along with the bindings and install it the .stack-work directory rather than `/usr/lib`? Earlier I decided against that because I thought it might piss off some sysadmins.

Another option is to use the linker to smush all the archives into one. 

Thoughts?

**Comment by jputcu** [comment]
Those are all valid options. I've learned that, if you want to reach many people, having many build options is the way to go, but providing a default which is very easy to get the `hello-world` going.
I don't have much time, but would love to put effort in the `fltkhs` project.

**Comment by deech** [comment]
That great news! I welcome and thank you in advance for your efforts.

Do you think that bundling `FLTK` should be the first step?

**Comment by deech** [comment]
Does https://github.com/deech/fltkhs/pull/51 fix this issue?

**Comment by jputcu** [comment]
Yep
