### ISSUE TITLE
Build fails to extract bundled fltk source

### ISSUE THREAD

**Issue by jputcu** [deech/fltkhs#66]
When building using stack, `stack build --flag fltkhs:bundled --verbose`, the process stops with following error:
~~~~
2017-09-11 14:45:05.132953: [info] Building bundled FLTK
@(Stack\Build\Execute.hs:1096:67)
2017-09-11 14:45:05.210953: [warn] tar: This does not look like a tar archive
@(Stack\Build\Execute.hs:1096:67)
2017-09-11 14:45:05.210953: [warn] tar: Skipping to next header
@(Stack\Build\Execute.hs:1096:67)
2017-09-11 14:45:05.429354: [warn] tar: Exiting with failure status due to previous errors
~~~~

I checked the version by printing from within the `Setup.hs` and it is the correct version and working directory. When using this version of `tar` to extract the archive, comment this line in the `Setup.hs`, calling the build again the build process passes this point and starts the configuration of the fltk library.

This is on a Windows 7.

**Comment by jputcu** [comment]
When I split the "untar" into an "gzip" and "tar" it works!

**Comment by deech** [comment]
Wow that's really odd. Splitting gunzipping and untarring seems pretty safe but just in case do you have a test branch so I can check if it works on other machines as well?

**Comment by jputcu** [comment]
Don't have a test branch. Don't know if it is worth it, because manually running the tar with unzip flag works. Going further on the stack build it fails with "rm missing operand". Manually running the configure and make in a mingw32 shell works! Perhaps my Windows environment is confused.

**Comment by jputcu** [comment]
Closing for now, until I can try on a clean install

**Comment by jputcu** [comment]
I have finally found what is going wrong: Everything is build within the `stack` environment which appears to be having problems.
~~~~
> stack exec tar tf fltk-1.3.4-1-source.tar.gz
/usr/bin/tar: This does not look like a tar archive
/usr/bin/tar: Skipping to next header
/usr/bin/tar: Exiting with failure status due to previous errors
~~~~~
