### ISSUE TITLE
Build fails with undefined reference to "Fl_awake_to_handler"

### ISSUE THREAD

**Issue by jputcu** [deech/fltkhs#73]
Latest development version fails to build on Windows:
~~~~
> stack build --flag fltkhs:bundled
....
Linking .stack-work\dist\5f9bc736\build\fltkhs-buttons\fltkhs-buttons.exe ...
C:\Users\jorisp\workspace\3rdparty\fltk\fltkhs\.stack-work\dist\5f9bc736\build/libHSfltkhs-0.5.4.4-EEy3JTZALO36A7zCpw2MLZ.a(FL.o):fake:(.text+0x136a): undefined reference to `Fl_awake_to_handler'
collect2.exe: error: ld returned 1 exit status
`g++' failed in phase `Linker'. (Exit code: 1)
~~~~

**Comment by deech** [comment]
I compiled it fine on my Windows 10 and I'm not seeing why it's failing on yours. It's there in the [C header file](https://github.com/deech/fltkhs/blob/master/c-src/Fl_C.h#L252), the [.cpp file](https://github.com/deech/fltkhs/blob/master/c-src/Fl_C.cpp#L572) and seems to be called just like the other functions from the [Haskell side](https://github.com/deech/fltkhs/blob/master/src/Graphics/UI/FLTK/LowLevel/FL.chs#L274). See anything I'm missing?

**Comment by jputcu** [comment]
Just did a long build on my laptop at home with Windows 10 and it completed, so will see if there is perhaps something other than `.stack-work` to remove before building on my Windows 7.

**Comment by sboosali** [comment]
This is probably unrelated, but I've gotten corrupt builds when changing
flags. And it's probably due to my ignorance about autotools et al, but:

@deech, should the custom setup.hs more aggressively purge with `cabal
clean` when its detected setting/unsettling flags? especially `-fopengl`.

**Comment by deech** [comment]
Yes it should. I run into this problem all the time with other flags as well (eg, `--profile`). I just haven't had time to do it yet. Another issue I've found is `stack clean` does not seem to call the `cleanHook` in `Setup.hs`.

**Comment by sboosali** [comment]
ha, just saw that you filed this issue years ago:

https://github.com/commercialhaskell/stack/issues/1890
