### ISSUE TITLE
Why isnt Op class Op op obj origObj impl | op obj origObj -> impl?

### ISSUE THREAD

**Issue by MarisaKirisame** [deech/fltkhs#78]
I am trying to build a within function, which take a window, a IO (), inject begin window, end window around the IO ().

However, I need to juggle the type so that the result of begin and end need to be returned, or ambiguous type will ensure.

Can we add a FunDep to avoid problem like this?

**Comment by sboosali** [comment]
iiuc, like the technique that supports variadic functions, this technique lets a method have implementations with different arities.

(But this might be wrong, since I'm not quite sure what you mean, without a concrete program, and because I'm not familiar with the Op typeclass either)

**Comment by MarisaKirisame** [comment]
@sboosali To me that sounds to be too little gain... Different arities can be done by uncurrying

**Comment by sboosali** [comment]
Yes, which requires records. However, a design goal of this package is making the many fltk examples (written in C), fltk being extensively documented.

**Comment by deech** [comment]
It can be done but it's ugly and it should really be part of the API but here's how to do it. Say you originally had something like :

```
ui :: IO ()
ui = do
 window <- windowNew ...
 begin window
 button <- buttonNew ...
 ...
 end window
 ...
```

If you only cared about `Window` and not any of it's subclasses (like `SingleWindow`, `DoubleWindow` etc.) you can do:

```
within :: Ref Window -> IO () -> IO ()
within window action = do
  begin window
  action
  end window

ui :: IO ()
ui = do
 window <- windowNew ...
 within window $ do
   button <- buttonNew ...
   ...
 ...
```

However if you want it to work for any `Window` it becomes ugly:

```
withinGeneric ::
  (
    Parent win Window,
    Match x ~ FindOp win win (Begin ()),
    Op (Begin ()) x win (IO ()),
    Match y ~ FindOp win win (End ()),
    Op (End ()) y win (IO ())
  )
  => Ref win -> IO () -> IO ()
withinGeneric ref' action = do
  () <- begin ref'
  action
  end ref'

ui :: IO ()
ui = do
 window <- windowNew ...
 withinGeneric window $ do
   button <- buttonNew ...
   ...
 ...
```

There's a lot of complexity here but in essence the `Parent win Window` constraint ensures that `win` is a "subclass" of `Window`, then the pair of `Match x ~ FindOp win win (Foo ()), Op (Foo ()) x win (IO ())` first finds a function called `begin` on `win` and then ensure that it's of type `IO ()`.

In any case this should be provided so feel free to leave this issue open and I'll add it to the API on the next release. You're also free to put up a PR if you want. :)

**Comment by deech** [comment]
And to answer your original question about FunDeps, I did try them originally but they didn't work because `impl` is a function signature like `(a -> b -> IO ())`. So for example, setting [the font size of a Widget](https://github.com/deech/fltkhs/blob/master/src/Graphics/UI/FLTK/LowLevel/Widget.chs#L274), `impl` is `(Font -> IO ())` which has to be a constraint which are ignored for the purposes of FunDeps.

**Comment by MarisaKirisame** [comment]
this is exactly what I do (and it work)
it is incredibly ugly though. I agree that it should be added into the library.
I will work on the PR :)
