### ISSUE TITLE
fltkhs-0.1.0.2 fails to build on OS X / Macports

### ISSUE THREAD

**Issue by HeinrichApfelmus** [deech/fltkhs#8]
Hello! I wanted to give `fltkhs` a try, but the build fails. Here's the build log:

    apfelmus$ cabal install fltkhs
    Resolving dependencies...
    Configuring fltkhs-0.1.0.2...
    Building fltkhs-0.1.0.2...
    Failed to install fltkhs-0.1.0.2
    Build log ( /Users/apfelmus/.cabal/logs/fltkhs-0.1.0.2.log ):
    [1 of 1] Compiling Main             ( /var/folders/st/qynp3xt166l2vqv1m78jq7_00000gr/T/fltkhs-0.1.0.2-42115/fltkhs-0.1.0.2/dist/setup/setup.hs, /var/folders/st/qynp3xt166l2vqv1m78jq7_00000gr/T/fltkhs-0.1.0.2-42115/fltkhs-0.1.0.2/dist/setup/Main.o )
    Linking /var/folders/st/qynp3xt166l2vqv1m78jq7_00000gr/T/fltkhs-0.1.0.2-42115/fltkhs-0.1.0.2/dist/setup/setup ...
    Running autoconf ...
    Warning: defaultUserHooks in Setup script is deprecated.
    Configuring fltkhs-0.1.0.2...
    configure: WARNING: unrecognized options: --with-hc, --with-gcc
    checking for g++... g++
    checking whether the C++ compiler works... yes
    checking for C++ compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking for gcc... gcc
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking for fltk-config... fltk-config
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking stddef.h usability... yes
    checking stddef.h presence... yes
    checking for stddef.h... yes
    checking for stdint.h... (cached) yes
    checking for stdlib.h... (cached) yes
    checking for string.h... (cached) yes
    checking for unistd.h... (cached) yes
    checking for main in -ldl... yes
    checking for fl_alphasort in -lfltk... no
    checking for main in -lfltk_gl... no
    checking for main in -lfltk_images... no
    checking for main in -lfltk_cairo... no
    checking for main in -lfltk_forms... no
    checking for size_t... yes
    checking for stdlib.h... (cached) yes
    checking for GNU libc compatible malloc... yes
    checking for select... yes
    checking for strdup... yes
    checking for strerror... yes
    checking for strrchr... yes
    checking for strtol... yes
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating c-src/Makefile
    config.status: creating c-examples/Makefile
    config.status: creating fltkhs.buildinfo
    configure: WARNING: unrecognized options: --with-hc, --with-gcc
    ==Compiling C bindings==
    *** Compiling Fl_Menu_ButtonC.cpp...
    *** Compiling Fl_PositionerC.cpp...
    *** Compiling Fl_TimerC.cpp...
    *** Compiling Fl_Value_OutputC.cpp...
    *** Compiling Fl_Value_SliderC.cpp...
    *** Compiling Fl_ScrollbarC.cpp...
    *** Compiling Fl_RollerC.cpp...
    *** Compiling Fl_DialC.cpp...
    *** Compiling Fl_CounterC.cpp...
    *** Compiling Utils.cpp...
    *** Compiling xC.cpp...
    *** Compiling fl_utf8C.cpp...
    *** Compiling glC.cpp...
    *** Compiling glutC.cpp...
    *** Compiling DerivedText_Editor.cpp...
    *** Compiling DerivedShared_Image.cpp...
    *** Compiling filenameC.cpp...
    *** Compiling Fl_AskC.cpp...
    *** Compiling Fl_BitmapC.cpp...
    *** Compiling Fl_BoxC.cpp...
    *** Compiling Fl_BrowserC.cpp...
    *** Compiling Fl_ButtonC.cpp...
    *** Compiling Fl_CallbackC.cpp...
    *** Compiling Fl_C.cpp...
    *** Compiling Fl_Check_ButtonC.cpp...
    *** Compiling Fl_ChoiceC.cpp...
    *** Compiling Fl_ClockC.cpp...
    *** Compiling Fl_Color_ChooserC.cpp...
    *** Compiling Fl_Copy_SurfaceC.cpp...
    *** Compiling Fl_Double_WindowC.cpp...
    *** Compiling Fl_DrawC.cpp...
    *** Compiling Fl_DeviceC.cpp...
    *** Compiling Fl_EnumerationsC.cpp...
    *** Compiling Fl_File_BrowserC.cpp...
    *** Compiling Fl_File_IconC.cpp...
    *** Compiling Fl_File_InputC.cpp...
    *** Compiling Fl_File_ChooserC.cpp...
    *** Compiling Fl_Float_InputC.cpp...
    *** Compiling Fl_Gl_WindowC.cpp...
    *** Compiling Fl_GroupC.cpp...
    *** Compiling Fl_Hold_BrowserC.cpp...
    *** Compiling Fl_Image_SurfaceC.cpp...
    *** Compiling Fl_ImageC.cpp...
    *** Compiling Fl_Input_C.cpp...
    *** Compiling Fl_InputC.cpp...
    *** Compiling Fl_Int_InputC.cpp...
    *** Compiling Fl_Light_ButtonC.cpp...
    *** Compiling Fl_Menu_C.cpp...
    *** Compiling Fl_Menu_ItemC.cpp...
    *** Compiling Fl_Multi_BrowserC.cpp...
    *** Compiling Fl_Multiline_InputC.cpp...
    *** Compiling Fl_Multiline_OutputC.cpp...
    *** Compiling Fl_Native_File_ChooserC.cpp...
    *** Compiling Fl_OutputC.cpp...
    *** Compiling Fl_Overlay_WindowC.cpp...
    *** Compiling Fl_Paged_DeviceC.cpp...
    *** Compiling Fl_PixmapC.cpp...
    *** Compiling Fl_PNM_ImageC.cpp...
    *** Compiling Fl_PreferencesC.cpp...
    *** Compiling Fl_PrinterC.cpp...
    *** Compiling Fl_ProgressC.cpp...
    *** Compiling Fl_Radio_ButtonC.cpp...
    *** Compiling Fl_Radio_Light_ButtonC.cpp...
    *** Compiling Fl_Repeat_ButtonC.cpp...
    *** Compiling Fl_Return_ButtonC.cpp...
    *** Compiling Fl_RGB_ImageC.cpp...
    *** Compiling Fl_Round_ButtonC.cpp...
    *** Compiling Fl_Round_ClockC.cpp...
    *** Compiling Fl_Secret_InputC.cpp...
    *** Compiling Fl_Select_BrowserC.cpp...
    *** Compiling Fl_Shared_ImageC.cpp...
    *** Compiling fl_show_colormapC.cpp...
    *** Compiling Fl_Single_WindowC.cpp...
    *** Compiling Fl_SliderC.cpp...
    *** Compiling Fl_Sys_Menu_BarC.cpp...
    *** Compiling Fl_TableC.cpp...
    *** Compiling Fl_Table_RowC.cpp...
    *** Compiling Fl_TabsC.cpp...
    *** Compiling Fl_Text_BufferC.cpp...
    *** Compiling Fl_Text_DisplayC.cpp...
    *** Compiling Fl_Text_EditorC.cpp...
    *** Compiling Fl_Text_SelectionC.cpp...
    *** Compiling Fl_TileC.cpp...
    *** Compiling Fl_Toggle_ButtonC.cpp...
    *** Compiling Fl_TooltipC.cpp...
    *** Compiling Fl_TreeC.cpp...
    *** Compiling Fl_Tree_ItemC.cpp...
    *** Compiling Fl_Tree_PrefsC.cpp...
    *** Compiling Fl_ValuatorC.cpp...
    *** Compiling Fl_AdjusterC.cpp...
    *** Compiling Fl_Value_InputC.cpp...
    *** Compiling Fl_WidgetC.cpp...
    *** Compiling Fl_WindowC.cpp...
    *** Compiling Fl_WizardC.cpp...
    *** Linking libfltkc.a...
    /opt/local/bin/ranlib: file: ../c-lib/libfltkc.a(fl_utf8C.o) has no symbols
    *** Not linking libfltkcdyn.dylib because of bugs in ./c-src/Makefile.in, help appreciated.
    Building fltkhs-0.1.0.2...
    Preprocessing library fltkhs-0.1.0.2...
    In file included from dist/build/Graphics/UI/FLTK/LowLevel/GlWindow.chs.h:2:
    In file included from ./c-src/Fl_C.h:5:
    ./c-src/Fl_Types.h:3:10: fatal error: 'FL/fl_types.h' file not found
    #include "FL/fl_types.h"
             ^
    1 error generated.
    c2hs: Error during preprocessing custom header file
    cabal: Error: some packages failed to install:
    fltkhs-0.1.0.2 failed during the building phase. The exception was:
    ExitFailure 1

I should note that I have installed the FLTK library via [Macports][1], which means that it has the prefix `/opt/local/`. The same is true for the `autoconf` tool.

  [1]: https://www.macports.org/

**Comment by deech** [comment]
Are you using FLTK version 1.3.3? There were some breaking changes between 1.3.2 and 1.3.3 and this binding is pretty tightly coupled to the latter.

**Comment by deech** [comment]
I take back what I just said, it seems as though it's not finding the header files that come with FLTK. I don't have immediate access to a Mac but is there some way to check where it sticks the header files and if your include path knows to look there?

**Comment by HeinrichApfelmus** [comment]
Here some output from the `fltk-config` program:

    apfelmus$ fltk-config --version
    1.3.3
    apfelmus$ fltk-config --includedir
    /opt/local/include
    apfelmus$ fltk-config --ldflags
    -L/opt/local/lib -Wl,-headerpad_max_install_names -lfltk -lpthread -framework Cocoa
    apfelmus$ fltk-config --cflags
    -I/opt/local/include -Os -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT

**Comment by deech** [comment]
The problem is that `gcc` on Mac does not seem to look for headers in "/opt/local/include" and I don't use the output of `fltk-config --cflags` to determine the location of header files. This is my fault.

When I tested it on a Mac I downloaded and compiled/installed it from scratch. It's easy, pretty much just: `configure; make; make install`. That put the headers in "/usr/local/include" which is in the default header search path. 

As a short-term solution I can recommend either that or simply adding "/opt/local/include" to `C_INCLUDE_PATH`.

I will update the package to use `fltk-config --cflags` output but hopefully this will get you up and running soon.

Apologies.

**Comment by deech** [comment]
I have fixed the repo is so that Cabal now uses `fltk-config` to determine the location of FLTK header files. Can you try it?

Thanks for your patience!

**Comment by HeinrichApfelmus** [comment]
Works now, thanks!

I have to remember to use 

    cabal install --ghc-options='-L/usr/lib'

though, otherwise GHC will link with the wrong `iconv` library. The `-L` argument ensures that GHC tries to check `/usr/lib` first and only then `/opt/local/lib`.

**Comment by deech** [comment]
Ah, good to know. Thanks! I'd be very interested in your feedback also.
