### ISSUE TITLE
within should allow returning stuff from inside

### ISSUE THREAD

**Issue by MarisaKirisame** [deech/fltkhs#80]
Ignoring typeclass issue, it should be of type Ref window -> IO a -> IO a

**Comment by MarisaKirisame** [comment]
BTW when will new fltkhs get released? I need to know so I can switch to the official wihin.

**Comment by deech** [comment]
Yes, you're right. I'll fix that and cut a new release sometime tomorrow.

**Comment by MarisaKirisame** [comment]
Cool
