### ISSUE TITLE
Giving a `handleCustom` function on a `TextDisplay` breaks text selection

### ISSUE THREAD

**Issue by plredmond** [deech/fltkhs#98]
Text selection with the mouse in a `TextDisplay` widget breaks when a trivial `handleCustom` function is provided. The same `handleCustom` function does *not* break text selection for `TextEditor`.

I've created an repro in haskell using fltkhs which demonstrates this problem.

https://gist.github.com/plredmond/065e47e7a060122b34872570d83d1938#file-textdisplay-hs

**Comment by plredmond** [comment]
I've created an example in c++ using bare fltk which demonstrates that this should work fine and that there may be a problem in fltkhs, or how I'm using it.

https://gist.github.com/plredmond/065e47e7a060122b34872570d83d1938#file-textdisplay-cpp

**Comment by deech** [comment]
Thanks for the example! There is indeed a problem with FLTKHS. Basically `handleSuper` is mistakenly delegating to `Group`'s `handle` instead of `TextDisplay`'s. I'm working on it.

**Comment by plredmond** [comment]
I started looking at the `.chs` code today but didn't make any progress yet. Thanks for looking into it!!

**Comment by deech** [comment]
It should be fixed in `HEAD` now, would you mind giving it a try and if it works for you I'll cut a release.

**Comment by deech** [comment]
I went ahead and released `fltkhs-0.7.0.3`, try changing the dependency and rebuilding. You'll probably want to do `stack clean` first.

**Comment by plredmond** [comment]
Sorry, I was working. Thanks for getting to this so fast! It works!! :)
