### ISSUE TITLE
Group docs list a resize taking TextDisplay as an argument

### ISSUE THREAD

**Issue by plredmond** [deech/fltkhs#99]
after #98 it seems something else broke

this page https://hackage.haskell.org/package/fltkhs-0.7.0.3/docs/Graphics-UI-FLTK-LowLevel-Group.html lists a function taking a `Ref TextDisplay`

```
resize :: Ref TextDisplay -> Rectangle -> IO ()
```

this function doesn't exist on the previous version https://hackage.haskell.org/package/fltkhs-0.7.0.2/docs/Graphics-UI-FLTK-LowLevel-Group.html

**Comment by deech** [comment]
Yes, you are right. And I found other stragglers as well. Sigh. Thanks for the bug report. I should have another release out shortly.

**Comment by deech** [comment]
This is fixed now. Please update your dependency to `fltkhs-0.7.0.4`. Thanks for your patience.

**Comment by plredmond** [comment]
No problem. You're super responsive. Sorry for making extra work! :)

I had to rm ~/.stack because of some problem with the indices not containing 0.7.0.4, so it is taking awhile for things to rebuild.

**Comment by plredmond** [comment]
Everything worked! Thanks again @deech!
